name = "JUPETER"
uuid = "34857a23-7c47-46ca-bf67-e70657f3fe6d"
authors = ["jjgomezcadenas <jjgomezcadenas@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
